TRAIN: 
  RESUMET_PATH: 
  BATCH_SIZE: 16 
  LEARNING_RATE: 1e-4 
  EVALUATE: False
  FINE_TUNE: False 
  BEGIN_EPOCH: 1
  END_EPOCH: 10 
SOLVER:
  MOMENTUM: 0.9
  WEIGHT_DECAY: 5e-4
  STEPS: [2, 3, 4, 5]
  LR_DECAY_RATE: 0.5
DATA: 
  MEAN: [0.4345, 0.4051, 0.3775]
  STD: [0.2768, 0.2713, 0.2737]
DATA_LOADER:
  NUM_WORKERS: 4
MODEL:
  NUM_CLASSES: 10
  BACKBONE: mobilenetv2
WEIGHTS:
  BACKBONE: 
  FREEZE_BACKBONE: False 
LISTDATA: 
  BASE_PTH: /home/ubuntu/workspace/BOHO_proj/Dataset/mall
  TRAIN_FILE: train.h5
  TEST_FILE: valid.h5
BACKUP_DIR: backup/person_counting
RNG_SEED:
